server:
  port: ${PORT:8761} 
  
spring:
  application:
     name: EurekaServiceV1  

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false 
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


logging:
  level:
    com.app.eurekaservice: INFO
  path:
    log
  file:
     ${logging.path}/eurekaService.log
     
